Modify pname and version in nixpkgs_metadata to fix pname conflicts
tweag/nixpkgs-graph-explorer pull request #88
Opened 2023-05-12 15:23 UTC by zz1874

Within this PR, we have made modifications to the `pname` and `version` attributes in `nixpkgs_metadata` by utilizing the `parseDrvName` function. 

This adjustment enables us to obtain accurate values for `pname` and `version`. The updated `pname` will help resolve conflicts in the UI, while retaining the original `pname` and `version` outside of `nixpkgs_metadata` for future reference.

fix #84

2023-05-12 16:07 UTC, GuillaumeDesforges requested changes
I don't think that's the right way to go about it.
The extracted data before this PR is right, the issue is probably in the graph database model or the UI.

2023-05-15 16:27 UTC, zz1874 commented
@GuillaumeDesforges Ah I might have misunderstood your point. 
Now, I keep the data itself as it should be, and change the data model and the ingestion process a bit to let it absorb the parsed `pname` rather than the `pname` from Nix.

2023-05-15 16:45 UTC, GuillaumeDesforges approved these changes
Let's fix that quickly

2023-05-15 16:45 UTC, GuillaumeDesforges commented on api/explorer/api/ingest.py
> +        graph.Package(pname=pkg.parsed_name.name, outputPath=op.path)
I don't think `pname` is a suitable name for this attribute in this `Package` data type

2023-05-15 16:46 UTC, merged